### ISSUE TITLE
`ltk_meta::BinTree` Missing Entries for Certain Champions (Aphelios skin0.bin)

### ISSUE THREAD

**Issue by DexalGT** [LeagueToolkit/league-toolkit#76]
## Summary

`ltk_meta::BinTree::from_reader()` fails to parse certain BIN entries, specifically `SkinCharacterDataProperties`, in some champion skin files. The Aphelios `skin0.bin` file is affected - the library parses only 99 VFX entries but **completely skips the main `SkinCharacterDataProperties` entry** that contains critical skin metadata.

## Environment

- **Crate**: `ltk_meta` (git main branch)
- **Rust version**: 1.x (stable)
- **BIN file**: `DATA/Characters/Aphelios/Skins/Skin0.bin` (from League client)
- **Comparison tool**: Original C++ ritobin (moonshadow565)

## Reproduction Steps

1. Extract `skin0.bin` for Aphelios from the League WAD (`aphelios.wad.client`)
2. Parse with `ltk_meta::BinTree::from_reader()`
3. Check `bin_tree.objects.len()` - shows **99 objects**
4. Convert to text with `ltk_ritobin::write()` or `ltk_ritobin::write_with_hashes()`
5. Observe: Only VFX particle entries are present, no `SkinCharacterDataProperties`

## Expected Behavior

The Aphelios `skin0.bin` should contain **100 entries** including:

```
"Characters/Aphelios/Skins/Skin0" = SkinCharacterDataProperties {
    skinClassification: u32 = 1
    championSkinName: string = "BaseAphelios"
    metaDataTags: string = "faction:mttargon,race:human,subfaction:lunari,gender:male,skinline:base"
    loadscreen: embed = CensoredImage {
        image: string = "ASSETS/Characters/Aphelios/Skins/Base/ApheliosLoadscreen.tex"
    }
    skinAudioProperties: embed = skinAudioProperties {
        tagEventList: list[string] = { "Aphelios" }
        bankUnits: list2[embed] = { ... }
    }
    skinMeshProperties: embed = SkinMeshDataProperties {
        skeleton: string = "..."
        simpleSkin: string = "..."
        ...
    }
    ...
}
```

## Actual Behavior

- `bin_tree.objects.len()` returns **99** (missing 1 entry)
- The `SkinCharacterDataProperties` entry is completely absent
- Only VFX entries like `VfxSystemDefinitionData` are parsed
- File roundtrip (read → write) produces identical byte size, but wrong interpretation

### Using original C++ ritobin:
```
entries: map[hash,embed] = {
    "Characters/Aphelios/Skins/Skin0" = SkinCharacterDataProperties {
        skinClassification: u32 = 1
        championSkinName: string = "BaseAphelios"
        ...
    }
    "Characters/Aphelios/Skins/Skin0/Particles/Aphelios_Base_Recall_weapons" = VfxSystemDefinitionData { ... }
    ... (98 more VFX entries)
}
```
Total: **100 entries**

### Using ltk_meta + ltk_ritobin:
```
entries: map[hash,embed] = {
    "Characters/Aphelios/Skins/Skin0/Particles/Aphelios_Base_BA_crescendum_mis_mini_self" = VfxSystemDefinitionData { ... }
    ... (98 more VFX entries)
}
```
Total: **99 entries** - `SkinCharacterDataProperties` is MISSING!

## Comparison with Working File

Yone's `skin0.bin` parses correctly with all entries including `SkinCharacterDataProperties`:
```
"Characters/Yone/Skins/Skin0" = SkinCharacterDataProperties {
    championSkinName: string = "Yone"
    skinAudioProperties: embed = SkinAudioProperties {
        bankUnits: list2[embed] = { ... }
    }
    ...
}
```

## File Details

- **Aphelios skin0.bin**: 665,412 bytes, PROP version 3
- **File magic**: "PROP"
- **Dependencies**: 6 linked BIN files

**Comment by alanpq** [comment]
I thought I fixed this exact issue before, will investigate

**Comment by alanpq** [comment]
I can't actually reproduce this issue. Running the example code from [this pr](https://github.com/LeagueToolkit/league-toolkit/pull/91) on the same aphelios bin, I do get a total of 99 objects, but I see the missing object:
```py
    "Characters/Aphelios/Skins/Skin0" = SkinCharacterDataProperties {
        skinClassification: u32 = 1
        championSkinName: string = "BaseAphelios"
        metaDataTags: string = "faction:mttargon,race:human,subfaction:lunari,gender:male,skinline:base"
        loadscreen: embed = CensoredImage {
            image: string = "ASSETS/Characters/Aphelios/Skins/Base/ApheliosLoadscreen.tex"
        }
        skinAudioProperties: embed = SkinAudioProperties {
          # ..
        }
        skinAnimationProperties: embed = SkinAnimationProperties {
            animationGraphData: link = "Characters/Aphelios/Animations/Skin0"
        }
        # ...
```
with the other 97 being `VfxSystemDefinitionData` entries. Should there still be 100 total objects? Are you still able to reproduce this on your end with the same code I used?

**Comment by DexalGT** [comment]
The issue was there everytime for me and converting with cpp ritobin gives 100 total objects and when i checked the differences only vfxemitters was converted (with some differences between variables and strings) 

However currently its fixed by crauzer and crauzer also merged the branch so it works correct now i didnt saw any bug in the updated version

**Comment by alanpq** [comment]
As in you still get 100 total objects? I only get 99 with current state of ltk

**Comment by DexalGT** [comment]
yeah i do get 100 total object currently result is exact same as cpp ritobin
